@section('content')
@include('componentslanding.hero')
@include('componentslanding.kategori')
@include('componentslanding.produk')
@include('componentslanding.tentang')
@include('componentslanding.artikel')
@include('componentslanding.testimoni')
@include('componentslanding.ajak')